### ISSUE TITLE
Invalid `useIsomorphicLayoutEffect` detection for React Native

### ISSUE THREAD

**Issue by andrejpavlovic** [satya164/use-latest-callback#3]
After trying to understand why the latest callback wasn't being set correctly in `@react/navigation` library, I realized that `useLayoutEffect` detection is broken when `useLatestCallback` is used in React Native.

https://github.com/satya164/use-latest-callback/blob/01ee54db826fca20a0867b1798aad1380bd675eb/src/index.ts#L3-L4

Current implementation doesn't take into account that `React.useLayoutEffect` is available even though `document` is not in React Native.

My suggestion would be to use [use-isomorphic-layout-effect](https://www.npmjs.com/package/use-isomorphic-layout-effect) library in order to support react native as well.

**Comment by satya164** [comment]
fixed in https://github.com/satya164/use-latest-callback/commit/e9bd09d937ae2519c16efe03635c8db3fb10dfbc
